export const endpoints = {
  authRefreshToken: "/api/auth/token",
  authLogin: "/api/auth/login",
  authRegister: "/api/auth/register",
  authGetProfile: "/api/auth/profile",
  authUpdateProfile: "/api/auth/profile",
  authLogout: "/api/auth/logout",
  authForgotPassword: "/api/auth/forgot-password",
  authResetPassword: "/api/auth/reset-password",
  authUploadAvatar: "/api/auth/avatar/upload",
  authChangePassword: "/api/auth/change-password",
  userGetInfo: "/api/users",
  messagesGet: "/api/messages",
  conversationsUploadPhoto: "/api/conversations/change-photo",
  conversationsChangeRole: "/api/conversations/change-role",
};
