export const endpoints = {
  authRefreshToken: "/auth/token",
  authLogin: "/auth/login",
  authRegister: "/auth/register",
  authGetProfile: "/auth/profile",
  authUpdateProfile: "/auth/profile",
  authLogout: "/auth/logout",
  authForgotPassword: "/auth/password/forgot",
  authResetPassword: "/auth/password/reset",
  authUploadAvatar: "/auth/avatar",
  authChangePassword: "/auth/change-password",
  userGetInfo: "/users",
  messagesGet: "/messages",
  conversations: "/conversations",
};
